data-module: experiment.qa.data.semeval.semeval
model-module: experiment.qa.model.cnn_lstm
training-module: experiment.qa.train.training_dynamic
evaluation-module: experiment.qa.evaluation.evaluation

logger:
  level: DEBUG
  path: logs/semeval-cnn-lstm.txt

global:
  question_length: 22
  answer_length: 200
  embedding_size: 100

data:
  lowercased: false
  embeddings_path: data/fasttext.webteb.100d.vec
  semeval: data/Semeval
  map_oov: true
  map_numbers: false

model:
  filters: 600
  filter_size: 3
  lstm_cell_size: 600
  margin: 0.2
  trainable_embeddings: true

training:
  save_folder: checkpoints/semeval-cnn-lstm
  epochs: 100
  early_stopping_patience: 4

  optimizer: sgd
  initial_learning_rate: 1.1
  dynamic_learning_rate: true
  dropout: 0.6

  scorer: map
  scorer_print:
    - accuracy
    - mrr

  negative_answers: 50
  negative_answers_valid: 500

  batchsize: 20
  batchsize_valid: 200
